### ISSUE TITLE
Mac Installation Error: ImportError: No module named 'urh.cythonext.signalFunctions'

### ISSUE THREAD

**Issue by rosstex** [jopohl/urh#142]
The full error after running ```pip install urh``` and ```urh``` (I have XCode installed and made sure pip was anaconda's) 

```
(py35) Rosss-MacBook-Air:discussion6 rosstex$ urh
Will not regenerate UI, because script cant be found. This is okay in release.
Could not find C++ extensions, trying to build them.
Traceback (most recent call last):
  File "/Users/rosstex/anaconda/envs/py35/lib/python3.5/site-packages/urh/main.py", line 49, in main
    import urh.cythonext.signalFunctions
ImportError: No module named 'urh.cythonext.signalFunctions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rosstex/anaconda/envs/py35/bin/urh", line 11, in <module>
    sys.exit(main())
  File "/Users/rosstex/anaconda/envs/py35/lib/python3.5/site-packages/urh/main.py", line 55, in main
    os.chdir(os.path.join(src_dir, "urh", "cythonext"))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/rosstex/anaconda/envs/src/urh/cythonext'
```

**Comment by jopohl** [comment]
Seems like the exentsion modules can be built. Could you tell me what happens when you:
```
git clone htttps://github.com/jopohl/urh
cd urh
python setup.py build_ext
```

**Comment by rosstex** [comment]
That seems to work fine. There's an error that "hackrf.h could not be found," but I assume that's because I don't use a hackrf radio.

**Comment by jopohl** [comment]
Thats okay, this just indicates that URH will be compiled without native HackRF support. I just published a new version to PyPi so could you try again with pip?

**Comment by jopohl** [comment]
Seems to be fixed.
