### ISSUE TITLE
Invalid syntax when I try to install or run the software - v1.3.7

### ISSUE THREAD

**Issue by bogdanr** [jopohl/urh#150]
When installing I get a bunch of errors like this:

```python
  File "/usr/lib64/python2.7/site-packages/urh-1.3.7-py2.7-linux-x86_64.egg/urh/controller/ProtocolLabelController.py", line 21
    def __init__(self, preselected_index, message: Message, viewtype: int, parent=None):
                                                 ^
SyntaxError: invalid syntax

  File "/usr/lib64/python2.7/site-packages/urh-1.3.7-py2.7-linux-x86_64.egg/urh/controller/ProjectDialogController.py", line 34
    def columnCount(self, parent: QModelIndex = None, *args, **kwargs):
                                ^
SyntaxError: invalid syntax

  File "/usr/lib64/python2.7/site-packages/urh-1.3.7-py2.7-linux-x86_64.egg/urh/controller/OptionsController.py", line 75
    def selected_device(self) -> BackendContainer:
                              ^
SyntaxError: invalid syntax

  File "/usr/lib64/python2.7/site-packages/urh-1.3.7-py2.7-linux-x86_64.egg/urh/controller/ModulatorDialogController.py", line 75
    def __set_gauss_ui_visibility(self, show: bool):
                                            ^
SyntaxError: invalid syntax

  File "/usr/lib64/python2.7/site-packages/urh-1.3.7-py2.7-linux-x86_64.egg/urh/controller/MessageTypeDialogController.py", line 16
    def __init__(self, message_type: MessageType, parent=None):
                                   ^
SyntaxError: invalid syntax

  File "/usr/lib64/python2.7/site-packages/urh-1.3.7-py2.7-linux-x86_64.egg/urh/controller/MainController.py", line 218
    def add_signalfile(self, filename: str, group_id=0):
                                     ^
SyntaxError: invalid syntax

  File "/usr/lib64/python2.7/site-packages/urh-1.3.7-py2.7-linux-x86_64.egg/urh/controller/GeneratorTabController.py", line 33
    def __init__(self, compare_frame_controller: CompareFrameController, project_manager: ProjectManager, parent=None):
                                               ^
SyntaxError: invalid syntax

  File "/usr/lib64/python2.7/site-packages/urh-1.3.7-py2.7-linux-x86_64.egg/urh/controller/FuzzingDialogController.py", line 13
    def __init__(self, protocol: ProtocolAnalyzerContainer, label_index: int, msg_index: int, proto_view: int, parent=None):
                               ^
SyntaxError: invalid syntax

  File "/usr/lib64/python2.7/site-packages/urh-1.3.7-py2.7-linux-x86_64.egg/urh/controller/DecoderWidgetController.py", line 21
    def __init__(self, decodings, signals, project_manager: ProjectManager,
                                                          ^
SyntaxError: invalid syntax

  File "/usr/lib64/python2.7/site-packages/urh-1.3.7-py2.7-linux-x86_64.egg/urh/controller/CompareFrameController.py", line 41
    def __init__(self, plugin_manager: PluginManager, project_manager: ProjectManager, parent):
                                     ^
SyntaxError: invalid syntax

  File "/usr/lib64/python2.7/site-packages/urh-1.3.7-py2.7-linux-x86_64.egg/urh/awre/CommonRange.py", line 5
    def __init__(self, start: int, end: int, bits: str):
                            ^
SyntaxError: invalid syntax

  File "/usr/lib64/python2.7/site-packages/urh-1.3.7-py2.7-linux-x86_64.egg/urh/awre/components/Preamble.py", line 63
    def __find_preamble_range(self, message: Message):
                                           ^
SyntaxError: invalid syntax

  File "/usr/lib64/python2.7/site-packages/urh-1.3.7-py2.7-linux-x86_64.egg/urh/awre/components/Length.py", line 138
    def find_lbl_function_in(function: FieldType.Function, message_type: MessageType) -> ProtocolLabel:
                                     ^
SyntaxError: invalid syntax

  File "/usr/lib64/python2.7/site-packages/urh-1.3.7-py2.7-linux-x86_64.egg/urh/awre/components/Component.py", line 11
    class Component(metaclass=ABCMeta):
                             ^
SyntaxError: invalid syntax
```

When trying to run it, I get this error:
```python
Traceback (most recent call last):
  File "/usr/bin/urh", line 9, in <module>
    load_entry_point('urh==1.3.7', 'console_scripts', 'urh')()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/python2.7/site-packages/urh-1.3.7-py2.7-linux-x86_64.egg/urh/main.py", line 30
    print("Time for generating UI: %.2f seconds" % (time.time() - t), file=sys.stderr)
                                                                          ^
SyntaxError: invalid synta
```

**Comment by andynoack** [comment]
It seems that you are using Python2 but URH requires at least Python3.4.
