### ISSUE TITLE
Crash when click analyze in the analysis tab

### ISSUE THREAD

**Issue by vsboost** [jopohl/urh#156]
Was playing with an ASK signal and program exits when i clicked the analyze button.

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urh/controller/CompareFrameController.py", line 1043, in on_btn_analyze_clicked
    self.proto_analyzer.auto_assign_labels()
  File "/usr/local/lib/python3.5/dist-packages/urh/signalprocessing/ProtocolAnalyzer.py", line 842, in auto_assign_labels
    format_finder = FormatFinder(self)
  File "/usr/local/lib/python3.5/dist-packages/urh/awre/FormatFinder.py", line 29, in __init__
    self.bitvectors = [np.array(msg.decoded_bits, dtype=np.int8) for msg in self.protocol.messages]
  File "/usr/local/lib/python3.5/dist-packages/urh/awre/FormatFinder.py", line 29, in <listcomp>
    self.bitvectors = [np.array(msg.decoded_bits, dtype=np.int8) for msg in self.protocol.messages]
TypeError: int() argument must be a string, a bytes-like object or a number, not 'src.urh.cythonext.signalFunctions.Symbol'
Aborted

**Comment by jopohl** [comment]
Thanks for reporting this @vsboost . I will have a look at this.

BTW: The analyze button is currently in a beta state. We are planning to supercharge it with some artificial intelligence in the future, so keep an eye on it. :wink:

**Comment by vsboost** [comment]
No probs :-)
