### ISSUE TITLE
signalFunctions cannot be imported

### ISSUE THREAD

**Issue by andynoack** [jopohl/urh#2]
/usr/bin/python-wrapper "/home/ryu/util/Eigene Dateien/Subversion/urh/bin/urh"
Time for generating UI: 1.24 seconds
Using modules from /home/ryu/util/Eigene Dateien/Subversion/urh/src
Traceback (most recent call last):
  File "/home/ryu/util/Eigene Dateien/Subversion/urh/bin/urh", line 72, in <module>
    os._exit(main(sys.argv)) # sys.exit() is not enough on Windows and will result in crash on exit
  File "/home/ryu/util/Eigene Dateien/Subversion/urh/bin/urh", line 32, in main
    from urh.controller.MainController import MainController
  File "/home/ryu/util/Eigene Dateien/Subversion/urh/src/urh/controller/MainController.py", line 12, in <module>
    from urh.controller.CompareFrameController import CompareFrameController
  File "/home/ryu/util/Eigene Dateien/Subversion/urh/src/urh/controller/CompareFrameController.py", line 12, in <module>
    from urh.controller.OptionsController import OptionsController
  File "/home/ryu/util/Eigene Dateien/Subversion/urh/src/urh/controller/OptionsController.py", line 6, in <module>
    from urh.controller.PluginController import PluginController
  File "/home/ryu/util/Eigene Dateien/Subversion/urh/src/urh/controller/PluginController.py", line 4, in <module>
    from urh.models.PluginListModel import PluginListModel
  File "/home/ryu/util/Eigene Dateien/Subversion/urh/src/urh/models/PluginListModel.py", line 5, in <module>
    from urh.plugins import Plugin
  File "/home/ryu/util/Eigene Dateien/Subversion/urh/src/urh/plugins/Plugin.py", line 7, in <module>
    from urh.signalprocessing.ProtocolAnalyzer import ProtocolAnalyzer
  File "/home/ryu/util/Eigene Dateien/Subversion/urh/src/urh/signalprocessing/ProtocolAnalyzer.py", line 10, in <module>
    from urh.cythonext import signalFunctions
ImportError: cannot import name 'signalFunctions'

**Comment by jopohl** [comment]
Please run src/urh/cythonext/build.py before running from source or install directly install with 
`sudo python setup.py install`
