### ISSUE TITLE
Array index out of range

### ISSUE THREAD

**Issue by vsboost** [jopohl/urh#290]
## Steps to Reproduce the Problem

  1.Press analyze / hide some fields
  2.Change some settings in interpreter i.e. error tolerance
  3.Go back to Analysis and click Analyze
  4. Program crash

## Platform Specifications

  - Python Version: 2.7.13
  - Operating System: Kali rolling latest
  - Version of URH: ran from master today

Traceback (most recent call last):
  File "/root/Downloads/urh/src/urh/controller/CompareFrameController.py", line 1011, in on_btn_analyze_clicked
    self.proto_analyzer.auto_assign_labels()
  File "/root/Downloads/urh/src/urh/signalprocessing/ProtocolAnalyzer.py", line 757, in auto_assign_labels
    format_finder.perform_iteration()
  File "/root/Downloads/urh/src/urh/awre/FormatFinder.py", line 75, in perform_iteration
    component.find_field(self.protocol.messages)
  File "/root/Downloads/urh/src/urh/awre/components/Component.py", line 58, in find_field
    self._py_find_field(messages)
  File "/root/Downloads/urh/src/urh/awre/components/Preamble.py", line 40, in _py_find_field
    rng = self.__find_preamble_range(msg)
  File "/root/Downloads/urh/src/urh/awre/components/Preamble.py", line 74, in __find_preamble_range
    first_difference = next((i for i in range(search_start, search_end-1) if bits[i] != bits[i+1]), None)
  File "/root/Downloads/urh/src/urh/awre/components/Preamble.py", line 74, in <genexpr>
    first_difference = next((i for i in range(search_start, search_end-1) if bits[i] != bits[i+1]), None)
IndexError: array index out of range
Aborted

**Comment by jopohl** [comment]
Thanks for reporting this @vsboost ! Just wrote a fix for it.
