### ISSUE TITLE
Error at launch time: ImportError: cannot import name 'auto_interpretation' 

### ISSUE THREAD

**Issue by trollwookiee** [jopohl/urh#680]
PR #550 causes an error at launch time: ImportError: cannot import name 'auto_interpretation' 

Between v2.3.0 and v2.4.0, #550 was merged (Enhance accuracy of automatic interpretation).
This PR introduces the ImportError: cannot import name 'auto_interpretation'

I have tested:

- v2.3.0: everything is OK
- v2.4.0: the ImportError occurs  
- all versions from v2.4.0 to master: the ImportError occurs  

It may be caused by my setup, but I have installed all dependencies: 
```
sudo` apt-get install python3-numpy python3-psutil python3-zmq python3-pyqt5 g++ libpython3-dev python3-pip cython3
```
and also made a git clean to remove private files

thanks for your help and keep up the great work. 

##### Actual Behavior
```
12:24 $ ./main.py 
Traceback (most recent call last):
  File "./main.py", line 179, in <module>
    main()
  File "./main.py", line 100, in main
    from urh.controller.MainController import MainController
  File "/home/tartopom/ism/sdr/urh/src/urh/controller/MainController.py", line 12, in <module>
    from urh.controller.CompareFrameController import CompareFrameController
  File "/home/tartopom/ism/sdr/urh/src/urh/controller/CompareFrameController.py", line 16, in <module>
    from urh.models.LabelValueTableModel import LabelValueTableModel
  File "/home/tartopom/ism/sdr/urh/src/urh/models/LabelValueTableModel.py", line 10, in <module>
    from urh.signalprocessing.ProtocolAnalyzer import ProtocolAnalyzer
  File "/home/tartopom/ism/sdr/urh/src/urh/signalprocessing/ProtocolAnalyzer.py", line 19, in <module>
    from urh.signalprocessing.Signal import Signal
  File "/home/tartopom/ism/sdr/urh/src/urh/signalprocessing/Signal.py", line 11, in <module>
    from urh.ainterpretation import AutoInterpretation
  File "/home/tartopom/ism/sdr/urh/src/urh/ainterpretation/AutoInterpretation.py", line 9, in <module>
    from urh.ainterpretation import Wavelet
  File "/home/tartopom/ism/sdr/urh/src/urh/ainterpretation/Wavelet.py", line 3, in <module>
    from urh.cythonext import auto_interpretation as  cy_auto_interpretation
ImportError: cannot import name 'auto_interpretation'
```
##### Platform Specifications
 - OS: Ubuntu 
 - URH version: 2.4.2 to 2.7.3
 - Python version: tested with 2.7 and 3.7
 - Installed via : Running from source

**Comment by jopohl** [comment]
Try rebuilding the cython extensions with

```
python3 src/urh/cythonext/build.py
```

and post the output of that script if it does not work afterwards.

**Comment by trollwookiee** [comment]
Thanks a lot for fast feedback, it was exactly that.
