### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by GF-Huang** [jopohl/urh#833]
```log
pi@raspberrypi:~ $ pip install urh 
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting urh
  Downloading https://www.piwheels.org/simple/urh/urh-2.9.1-cp37-cp37m-linux_armv7l.whl (4.8 MB)
     |████████████████████████████████| 4.8 MB 146 kB/s 
Requirement already satisfied: psutil in /usr/lib/python3/dist-packages (from urh) (5.5.1)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from urh) (1.16.2)
Collecting cython
  Downloading https://www.piwheels.org/simple/cython/Cython-0.29.21-cp37-cp37m-linux_armv7l.whl (4.7 MB)
     |████████████████████████████████| 4.7 MB 8.0 MB/s 
Collecting pyqt5
  Downloading PyQt5-5.15.2.tar.gz (3.3 MB)
     |████████████████████████████████| 3.3 MB 3.4 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /home/pi/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp14yutv4h
         cwd: /tmp/pip-install-bslj44hp/pyqt5_caf4821bf5f846eda2a412b93de2ad69
    Complete output (31 lines):
    Traceback (most recent call last):
      File "/home/pi/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 126, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/pi/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/home/pi/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/pi/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 131, in prepare_metadata_for_build_wheel
        config_settings)
      File "/home/pi/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 159, in _get_wheel_metadata_from_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/tmp/pip-build-env-2hbgdzkn/overlay/lib/python3.7/site-packages/sipbuild/api.py", line 51, in build_wheel
        project = AbstractProject.bootstrap('pep517')
      File "/tmp/pip-build-env-2hbgdzkn/overlay/lib/python3.7/site-packages/sipbuild/abstract_project.py", line 83, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "/tmp/pip-build-env-2hbgdzkn/overlay/lib/python3.7/site-packages/sipbuild/project.py", line 479, in setup
        self.apply_user_defaults(tool)
      File "project.py", line 63, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/tmp/pip-build-env-2hbgdzkn/overlay/lib/python3.7/site-packages/pyqtbuild/project.py", line 79, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/tmp/pip-build-env-2hbgdzkn/overlay/lib/python3.7/site-packages/sipbuild/project.py", line 225, in apply_user_defaults
        self.builder.apply_user_defaults(tool)
      File "/tmp/pip-build-env-2hbgdzkn/overlay/lib/python3.7/site-packages/pyqtbuild/builder.py", line 67, in apply_user_defaults
        "specify a working qmake or add it to PATH")
    sipbuild.pyproject.PyProjectOptionException
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /home/pi/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp14yutv4h Check the logs for full command output.
pi@raspberrypi:~ $ sudo pip install urh 
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting urh
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/urh/
  Downloading https://files.pythonhosted.org/packages/ea/ec/f091b8dd7636c1999a0cef0d6d0c5fe011e12e9a4c1809526bfa58c39197/urh-2.9.1.tar.gz (2.9MB)
    100% |████████████████████████████████| 2.9MB 87kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-urM8k7/urh/setup.py", line 44
        file=sys.stderr)
            ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-urM8k7/urh/

```

**Comment by jopohl** [comment]
Try 
```bash
sudo python3 -m pip install urh
```
