### ISSUE TITLE
Fails to launch on Debian

### ISSUE THREAD

**Issue by Spessmen14** [jopohl/urh#885]
installed per instructions for linux.

When launching get the following:
Traceback (most recent call last):
  File "/usr/local/bin/urh", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/urh/main.py", line 84, in main
    import urh.cythonext.signal_functions
  File "src/urh/cythonext/signal_functions.pyx", line 1, in init urh.cythonext.signal_functions
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**Comment by jopohl** [comment]
Fix can be found here: https://github.com/jopohl/urh/discussions/878
